options:
  template:
    type: string
    default: |
      input {
        elasticsearch {
          hosts => {{ hosts }}
          index => "logstash-input-elasticsearch-*"
          query => '{"query": { "match_all": {} } }'
          scroll => "5m"
        }
      }
    description: "See https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elasticsearch.html Use template variable 'hosts' for list of connected elasticsearch servers"
